run:
  # TODO: re-enable tests linting and make them pass
  tests: false

linters-settings:
  dupl:
    threshold: 400
  gocyclo:
    min-complexity: 15
  cyclop:
    max-complexity: 15
  govet:
    enable-all: true
    disable:
      - fieldalignment
  lll:
    line-length: 170
    tab-width: 4
  depguard:
    rules:
      main:
        allow:
          - $gostd
          - github.com/bitpoke
          - github.com/presslabs
          - github.com/appscode
          - github.com/cooleo
          - github.com/go-logr
          - github.com/onsi
          - github.com/spf13
          - k8s.io
          - sigs.k8s.io
          - golang.org
          - gomodules.xyz

linters:
  presets:
    - bugs
    - unused
    - format
    - style
    - complexity
    - performance

  disable:
    - gochecknoglobals
    - gochecknoinits
    - wrapcheck
    - exhaustruct
    # TODO: fix those linters (they were added for 1.42.1 upgrade)
    - gci
    # new linters not previously active - disable to keep upgrade minimal
    - tagalign
    - contextcheck
    - depguard
    - execinquery
    - ireturn
    - nonamedreturns
    - perfsprint
    - usestdlibvars
    - varnamelen
    - wsl
    - forcetypeassert
    - nolintlint

issues:
  max-same-issues: 0
  exclude-use-default: false
  exclude:
    # gosec G104, about unhandled errors. We do that with errcheck already
    - "G104: Errors unhandled"
    - "mnd: "
    - "Line contains TODO/BUG/FIXME"
  exclude-rules:
    - linters:
        - godox
      text: "TODO:"
    - linters:
      # Ignore package comments (ST1000) since most of the time are irrelevant
      - stylecheck
      text: "ST1000"
    - linters:
        - revive
      text: "package-comments"
